### ISSUE TITLE
Consume not behaving as expected when autoconsume is disabled.

### ISSUE THREAD

**Issue by s3c** [guruofquality/grextras#16]
When autoconsume is disabled even the basic example given in the wiki throws an exception. I've narrowed it down as much as possible, the following block:
# !/usr/bin/env python

from gnuradio import gr
from gnuradio.extras import block_gateway
import numpy

class my_basic_pass_block(gr.block):
  def **init**(self):
    gr.block.**init**(self, name="my_basic_pass_block", in_sig=[numpy.float32], out_sig=[numpy.float32])
    self.set_auto_consume(False)

  def forecast(self, noutput_items, ninput_items_required):
    ninput_items_required[0] = noutput_items

  def work(self, input_items, output_items):
    in0 = input_items[0]
    out = output_items[0]
    out[:] = in0
    self.consume(0, len(in0))
    return len(out)

Crashes with this message:

handler caught exception: operands could not be broadcast together with shapes (8192) (16383) 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/extras/block_gateway.py", line 53, in eval
    try: self._callback()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/extras/block_gateway.py", line 124, in __gr_block_handle
    ) for i in self.__out_indexes],
  File "/home/user/mygnuradioblocks/my_basic_pass_block.py", line 18, in work
    out[:] = in0
ValueError: operands could not be broadcast together with shapes (8192) (16383) 
thread[thread-per-block[1]: <gr_block my_basic_pass_block (9)>]: caught unrecognized exception

But when commenting out the self.consume and self.set_auto_consume lines it works as expected.

**Comment by guruofquality** [comment]
There is no fixed relationship between the input and output lengths. The error in  out[:] = in0 is expected. Try using an index

**Comment by s3c** [comment]
Thanks for the reply Josh, could you perhaps update the example code for this? I took this code pretty much entirely from here:

https://github.com/guruofquality/grextras/wiki/Blocks-Coding-Guide#wiki-arbitrary-ratio-block

And just modified it to compile.

**Comment by guruofquality** [comment]
It may have been some copypasta. Wiki page updated!
