### ISSUE TITLE
make test errors

### ISSUE THREAD

**Issue by tjt7a** [guruofquality/grextras#19]
## I was building grextras on a 32-bit Ubuntu 10.04 machine, when the build tests failed:

tjt7a@bt:~/src/grextras/build$ ctest
Test project /home/tjt7a/src/grextras/build
    Start 1: qa_add_and_friends
1/9 Test #1: qa_add_and_friends ...............**_Failed    0.23 sec
    Start 2: qa_block_gateway
2/9 Test #2: qa_block_gateway .................   Passed    0.24 sec
    Start 3: qa_delay
3/9 Test #3: qa_delay .........................   Passed    0.19 sec
    Start 4: qa_noise_source
4/9 Test #4: qa_noise_source ..................**_Failed    0.20 sec
    Start 5: qa_signal_source
5/9 Test #5: qa_signal_source .................   Passed    0.20 sec
    Start 6: qa_pmt
6/9 Test #6: qa_pmt ...........................**_Failed    0.20 sec
    Start 7: qa_msg_passing
7/9 Test #7: qa_msg_passing ...................**_Failed    0.83 sec
    Start 8: qa_pmt_to_python
8/9 Test #8: qa_pmt_to_python .................   Passed    0.20 sec
    Start 9: qa_pmt_rpc
9/9 Test #9: qa_pmt_rpc .......................   Passed    2.21 sec

56% tests passed, 4 tests failed out of 9

Total Test time (real) =   4.51 sec

The following tests FAILED:
      1 - qa_add_and_friends (Failed)
      4 - qa_noise_source (Failed)
      6 - qa_pmt (Failed)
      7 - qa_msg_passing (Failed)
Errors while running CTest
## I then looked more closely at the qa_msg_passing test and got the following:

tjt7a@bt:~/src/grextras/build$ ctest -VV -R qa_msg
UpdateCTestConfiguration  from :/home/tjt7a/src/grextras/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/tjt7a/src/grextras/build/DartConfiguration.tcl
Test project /home/tjt7a/src/grextras/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
test 7
    Start 7: qa_msg_passing

7: Test command: /bin/sh /home/tjt7a/src/grextras/build/python/qa_msg_passing_test.sh
7: Test timeout computed to be: 9.99988e+06
7: linux; GNU C++ version 4.4.3; Boost_104000; UHD_003.005.001-release
7: 
7: EEE
7: ======================================================================
7: ERROR: test_disconnect (**main**.test_msg_passing)
7: ----------------------------------------------------------------------
7: Traceback (most recent call last):
7:   File "/home/tjt7a/src/grextras/python/qa_msg_passing.py", line 133, in test_disconnect
7:     self.assertItemsEqual(sink.msgs(), msgs)
7: AttributeError: 'test_msg_passing' object has no attribute 'assertItemsEqual'
7: 
7: ======================================================================
7: ERROR: test_hier (**main**.test_msg_passing)
7: ----------------------------------------------------------------------
7: Traceback (most recent call last):
7:   File "/home/tjt7a/src/grextras/python/qa_msg_passing.py", line 103, in test_hier
7:     self.assertItemsEqual(sink.msgs(), msgs)
7: AttributeError: 'test_msg_passing' object has no attribute 'assertItemsEqual'
7: 
7: ======================================================================
7: ERROR: test_top (**main**.test_msg_passing)
7: ----------------------------------------------------------------------
7: Traceback (most recent call last):
7:   File "/home/tjt7a/src/grextras/python/qa_msg_passing.py", line 84, in test_top
7:     self.assertItemsEqual(sink.msgs(), msgs)
7: AttributeError: 'test_msg_passing' object has no attribute 'assertItemsEqual'
7: 
7: ----------------------------------------------------------------------
7: Ran 3 tests in 0.314s
7: 
7: FAILED (errors=3)
1/1 Test #7: qa_msg_passing ...................***Failed    0.84 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.84 sec

The following tests FAILED:
      7 - qa_msg_passing (Failed)
Errors while running CTest

**Comment by guruofquality** [comment]
Unfortunately, assertItemsEqual is not in the python unittest library in ubuntu 10.04. I guess that this call was a more recent edition. Not sure if I would create a work-a-round or just ignore the issue. 10.04 is getting quite old these days :-)
