### ISSUE TITLE
please update for compatibility gnu radio 3.7

### ISSUE THREAD

**Issue by sbrun** [guruofquality/grextras#38]
gr-extras doesn't work with gnu-radio 3.7: gruel and core are replaced by runtime as mentionned on this page (it may be helpful):
http://gnuradio.org/redmine/projects/gnuradio/wiki/Move_3-6_to_3-7
thanks

**Comment by marcusmueller** [comment]
@sbrun: @guruofquality is surely _very_ aware of the differences between GR 3.6 and 3.7. Also, a vast part of the functionality in the 3.6-compatible gr-extras has made its way into GR 3.7; there's message passing, extended PMT helpers, and even python blocks!

**Comment by guruofquality** [comment]
Sorry that I didn't answer this right away, but for those still watching, here is the story:

So, in the middle of GRAS development, I realized that GRAS was taking too long to develop and that some of the useful features like message passing and python blocks could be sort of hacked into an out of tree project which could be built against the stock scheduler. So gr-extras was born:

It had a unified block API, message passing, and python bindings for all of the features. The message passing was actually implemented over the tag streams using separate blocks for each message port, and so each gr-extras block was a hierarchy of gnuradio blocks (at least under the hood). We ended up doing some neat demos with gr-extras and pre-cog.  I suspect that users still coming to gr-extras are trying to run the old pre-cog demos. 

Anyway, features from gr-extras slowly made their way into gnuradio in one form or another, and most of the GRAS development was coming to completion. So when gnuradio 3.7 came out, it had major file name changes, changes that overlapped with the gr-extras unified block API. So I took this as an opportunity to retire gr-extras to gnuradio 3.6 series. 

Fast-forward in time. I am working on Pothos now, and the spirit and passion of what I did in gr-extras and GRAS very much lives on:
- Here is the main wiki page for the Pothos project: https://github.com/pothosware/pothos/wiki
- I kept up with the idea of a unified block API and continued to polish it.  So far this has worked out great for every kind of block, whether synchronous IOs, rate changing, variable, message driven... Check out the coding guide for an in-detail look: https://github.com/pothosware/pothos-library/wiki/BlocksCodingGuide
- I continued to develop the message passing feature. All ports are capable of asynchronous message passing: https://github.com/pothosware/pothos-library/wiki/BlocksCodingGuide#messaging-api
- Buffers can be easily lifted between message (packet) domains and stream domains without copying: https://github.com/pothosware/pothos-library/wiki/BlocksCodingGuide#buffer-access-api
- When messages are not used for streaming, but rather control and configuration, I formalized this use case into the signals and slots API: https://github.com/pothosware/pothos-library/wiki/BlocksCodingGuide#signals-and-slots-api
- And here is a very slick demo using signals and slots in the GUI to control SDR hardware: https://github.com/pothosware/pothos-sdr/wiki#control-demonstration
